{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1d65d37-6a53-4473-beae-4c7d8a2ea3fa",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-06-27T22:07:38.500968Z",
     "iopub.status.busy": "2022-06-27T22:07:38.500673Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:00<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   0%|          | 0/71 [00:01<?, ?it/s]\n",
      "Metadata Fetch Progress:   1%|▏         | 1/71 [00:02<00:10,  6.94it/s]\n",
      "Metadata Fetch Progress:   3%|▎         | 2/71 [00:02<00:20,  3.36it/s]\n",
      "Metadata Fetch Progress:   6%|▌         | 4/71 [00:02<00:09,  6.97it/s]\n",
      "Metadata Fetch Progress:   8%|▊         | 6/71 [00:02<00:06,  9.33it/s]\n",
      "Metadata Fetch Progress:  10%|▉         | 7/71 [00:02<00:06,  9.20it/s]\n",
      "Metadata Fetch Progress:  11%|█▏        | 8/71 [00:02<00:07,  8.46it/s]\n",
      "Metadata Fetch Progress:  14%|█▍        | 10/71 [00:03<00:05, 10.78it/s]\n",
      "Metadata Fetch Progress:  17%|█▋        | 12/71 [00:03<00:05, 11.49it/s]\n",
      "Metadata Fetch Progress:  20%|█▉        | 14/71 [00:03<00:05, 10.86it/s]\n",
      "Metadata Fetch Progress:  23%|██▎       | 16/71 [00:03<00:04, 11.14it/s]\n",
      "Metadata Fetch Progress:  25%|██▌       | 18/71 [00:03<00:04, 10.96it/s]\n",
      "Metadata Fetch Progress:  28%|██▊       | 20/71 [00:03<00:04, 11.44it/s]\n",
      "Metadata Fetch Progress:  32%|███▏      | 23/71 [00:04<00:03, 14.84it/s]\n",
      "Metadata Fetch Progress:  35%|███▌      | 25/71 [00:04<00:05,  8.45it/s]\n",
      "Metadata Fetch Progress:  39%|███▉      | 28/71 [00:04<00:03, 11.00it/s]\n",
      "Metadata Fetch Progress:  42%|████▏     | 30/71 [00:04<00:03, 10.79it/s]\n",
      "Metadata Fetch Progress:  45%|████▌     | 32/71 [00:05<00:03, 12.31it/s]\n",
      "Metadata Fetch Progress:  48%|████▊     | 34/71 [00:05<00:05,  6.92it/s]\n",
      "Metadata Fetch Progress:  56%|█████▋    | 40/71 [00:05<00:02, 12.34it/s]\n",
      "Metadata Fetch Progress:  59%|█████▉    | 42/71 [00:05<00:02, 12.32it/s]\n",
      "Metadata Fetch Progress:  62%|██████▏   | 44/71 [00:06<00:03,  8.89it/s]\n",
      "Metadata Fetch Progress:  65%|██████▍   | 46/71 [00:06<00:02,  8.73it/s]\n",
      "Metadata Fetch Progress:  68%|██████▊   | 48/71 [00:06<00:02,  8.82it/s]\n",
      "Metadata Fetch Progress:  72%|███████▏  | 51/71 [00:06<00:01, 11.63it/s]\n",
      "Metadata Fetch Progress:  75%|███████▍  | 53/71 [00:07<00:01, 11.97it/s]\n",
      "Metadata Fetch Progress:  77%|███████▋  | 55/71 [00:07<00:01,  9.72it/s]\n",
      "Metadata Fetch Progress:  80%|████████  | 57/71 [00:07<00:01, 11.10it/s]\n",
      "Metadata Fetch Progress:  83%|████████▎ | 59/71 [00:07<00:01,  8.32it/s]\n",
      "Metadata Fetch Progress:  86%|████████▌ | 61/71 [00:08<00:01,  7.99it/s]\n",
      "Metadata Fetch Progress:  89%|████████▊ | 63/71 [00:08<00:01,  6.35it/s]\n",
      "Metadata Fetch Progress:  90%|█████████ | 64/71 [00:08<00:01,  6.42it/s]\n",
      "Metadata Fetch Progress:  92%|█████████▏| 65/71 [00:09<00:01,  5.76it/s]\n",
      "Metadata Fetch Progress:  93%|█████████▎| 66/71 [00:09<00:00,  5.35it/s]\n",
      "Metadata Fetch Progress:  94%|█████████▍| 67/71 [00:09<00:00,  4.14it/s]\n",
      "Metadata Fetch Progress:  97%|█████████▋| 69/71 [00:09<00:00,  5.78it/s]\n",
      "Metadata Fetch Progress:  99%|█████████▊| 70/71 [00:10<00:00,  3.84it/s]\n",
      "Metadata Fetch Progress: 100%|██████████| 71/71 [00:10<00:00,  6.54it/s]\n",
      "Read:  20%|█▉        | 39/200 [00:44<04:50,  1.80s/it]\u001b[2m\u001b[36m(raylet, ip=172.31.30.202)\u001b[0m Spilled 2257 MiB, 5 objects, write throughput 79 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.\n",
      "2022-06-27 22:08:46,192\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "Read:  20%|██        | 40/200 [00:53<09:44,  3.65s/it]2022-06-27 22:08:46,207\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "\u001b[2m\u001b[36m(raylet, ip=172.31.19.115)\u001b[0m Spilled 4115 MiB, 11 objects, write throughput 123 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.\n",
      "Read:  21%|██        | 42/200 [00:55<05:54,  2.25s/it]\u001b[2m\u001b[36m(raylet, ip=172.31.30.202)\u001b[0m Spilled 5330 MiB, 13 objects, write throughput 151 MiB/s.\n",
      "Read:  23%|██▎       | 46/200 [00:57<02:30,  1.02it/s]\u001b[2m\u001b[36m(raylet, ip=172.31.19.115)\u001b[0m Spilled 5123 MiB, 13 objects, write throughput 142 MiB/s.\n",
      "Read:  24%|██▎       | 47/200 [00:57<01:56,  1.32it/s]2022-06-27 22:08:53,218\tWARNING worker.py:1404 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 41653f7ea1b3c7a10ad1ab8a9dd79a1ce6d666390e000000 Worker ID: 958b7e687293ab4d890b6b4e370420925d96fda0ad19d9d8403c8860 Node ID: 017862cb2c386573f2c7de1beae30271958e1fb716a173404851b31e Worker IP address: 172.31.28.127 Worker port: 10112 Worker PID: 27676\n",
      "Read:  26%|██▌       | 51/200 [01:05<04:10,  1.68s/it]2022-06-27 22:08:58,465\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "Read:  26%|██▌       | 52/200 [01:05<03:06,  1.26s/it]\u001b[2m\u001b[36m(raylet, ip=172.31.19.115)\u001b[0m Spilled 9753 MiB, 16 objects, write throughput 228 MiB/s.\n",
      "2022-06-27 22:08:59,345\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "2022-06-27 22:08:59,349\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "2022-06-27 22:08:59,354\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "2022-06-27 22:08:59,355\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "2022-06-27 22:08:59,444\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "2022-06-27 22:08:59,447\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "2022-06-27 22:08:59,890\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "\u001b[2m\u001b[36m(raylet, ip=172.31.19.115)\u001b[0m Spilled 36480 MiB, 30 objects, write throughput 855 MiB/s.\n",
      "Read:  28%|██▊       | 55/200 [01:09<02:52,  1.19s/it]\u001b[2m\u001b[36m(raylet, ip=172.31.19.115)\u001b[0m Spilled 36681 MiB, 31 objects, write throughput 852 MiB/s.\n",
      "Read:  30%|███       | 60/200 [01:15<02:21,  1.01s/it]\u001b[2m\u001b[36m(raylet, ip=172.31.30.202)\u001b[0m Spilled 9291 MiB, 17 objects, write throughput 162 MiB/s.\n",
      "Read:  35%|███▌      | 70/200 [01:28<01:48,  1.20it/s]\u001b[2m\u001b[36m(raylet)\u001b[0m Spilled 8921 MiB, 415 objects, write throughput 146 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.\n",
      "Read:  42%|████▏     | 84/200 [01:33<00:27,  4.17it/s]\u001b[2m\u001b[36m(raylet)\u001b[0m Spilled 9473 MiB, 429 objects, write throughput 149 MiB/s.\n",
      "Read:  44%|████▎     | 87/200 [01:37<01:48,  1.04it/s]\u001b[2m\u001b[36m(raylet)\u001b[0m Spilled 9749 MiB, 434 objects, write throughput 151 MiB/s.\n",
      "Read:  62%|██████▎   | 125/200 [02:06<00:43,  1.71it/s]2022-06-27 22:10:01,098\tWARNING worker.py:1404 -- Traceback (most recent call last):\n",
      "  File \"python/ray/_raylet.pyx\", line 896, in ray._raylet.spill_objects_handler\n",
      "  File \"python/ray/_raylet.pyx\", line 899, in ray._raylet.spill_objects_handler\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 662, in spill_objects\n",
      "    return _external_storage.spill_objects(object_refs, owner_addresses)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 303, in spill_objects\n",
      "    return self._write_multiple_objects(f, object_refs, owner_addresses, url)\n",
      "  File \"/home/hadoop/.local/lib/python3.7/site-packages/ray/external_storage.py\", line 145, in _write_multiple_objects\n",
      "    + memoryview(buf)\n",
      "MemoryError\n",
      "An unexpected internal error occurred while the IO worker was spilling objects: \n",
      "Read:  63%|██████▎   | 126/200 [03:46<35:58, 29.17s/it]"
     ]
    }
   ],
   "source": [
    "import ray\n",
    "import pyarrow as pa\n",
    "\n",
    "ray.init(address=\"172.31.28.127:6379\")\n",
    "\n",
    "def cast(t: pa.Table) -> pa.Table:\n",
    "    schema = t.schema\n",
    "    field_idx = schema.get_field_index(\"review_body\")\n",
    "    field = schema.field(field_idx)\n",
    "    new_field = field.with_type(pa.large_string())\n",
    "    new_schema = schema.set(field_idx, new_field)\n",
    "    return t.cast(new_schema)\n",
    "\n",
    "ds = ray.data.read_parquet(\"s3://dsoaws/parquet/\", _block_udf=cast)\n",
    "\n",
    "ds.groupby(\"product_category\").count().show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "390b8312-fbd8-462f-9534-dd48e5173447",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
